create table
  public.actions (
    id bigint generated by default as identity,
    occured_at timestamp with time zone not null default now(),
    action_type boolean not null,
    target_type boolean not null,
    initiator_id uuid not null,
    target_id uuid not null,
    constraint actions_pkey primary key (id),
    constraint actions_initiator_id_fkey foreign key (initiator_id) references auth.users (id) on update restrict on delete restrict
  ) tablespace pg_default;